services:
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: ${POSTGRES_PGDATA}
    volumes:
      - vocabulary_postgres_data:${POSTGRES_PGDATA}
    networks:
      - vocabulary-network

  # translate:
  #   image: libretranslate/libretranslate
  #   container_name: translate
  #   ports:
  #     - '${TRANSLATE_PORT}:${TRANSLATE_PORT}'
  #   environment:
  #     LT_PORT: ${TRANSLATE_PORT}
  #     LT_LOAD_ONLY: ${TRANSLATE_LOAD_ONLY}
  #     LT_DISABLE_WEB_UI: ${TRANSLATE_DISABLE_WEB_UI}
  #     LT_DISABLE_FILES_TRANSLATION: ${TRANSLATE_DISABLE_FILES_TRANSLATION}

  api:
    build:
      context: ../
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "3000:3000"
    restart: unless-stopped
    depends_on:
      - postgres
    networks:
      - vocabulary-network

  frontend:
    build:
      context: ../ui
      dockerfile: Dockerfile
    ports:
      - "80:5173"
    restart: unless-stopped
    depends_on:
      - api
    networks:
      - vocabulary-network
    environment:
      - NODE_ENV=production

volumes:
  vocabulary_postgres_data:

networks:
  vocabulary-network:
    driver: bridge