services:
  postgres:
    image: postgres:13
    container_name: postgres
    ports:
      - '${POSTGRES_PORT}:5432'
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: ${POSTGRES_PGDATA}
    volumes:
      - vocabulary_postgres_data:${POSTGRES_PGDATA}

  translate:
    image: libretranslate/libretranslate
    container_name: translate
    ports:
      - '${TRANSLATE_PORT}:${TRANSLATE_PORT}'
    environment:
      LT_PORT: ${TRANSLATE_PORT}
      LT_LOAD_ONLY: ${TRANSLATE_LOAD_ONLY}
      LT_DISABLE_WEB_UI: ${TRANSLATE_DISABLE_WEB_UI}
      LT_DISABLE_FILES_TRANSLATION: ${TRANSLATE_DISABLE_FILES_TRANSLATION}

volumes:
  vocabulary_postgres_data:
