services:
  postgres:
    image: postgres:13
    container_name: postgres_db
    ports:
      - '${POSTGRES_PORT}:5432'
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: ${POSTGRES_PGDATA}
    volumes:
      - postgres_data:${POSTGRES_PGDATA}

  translate:
    image: libretranslate/libretranslate
    container_name: translate
    ports:
      - '${TRANSLATE_PORT}:${LT_PORT}'
    environment:
      LT_PORT: ${LT_PORT}
      LT_LOAD_ONLY: ${LT_LOAD_ONLY}
      LT_DISABLE_WEB_UI: ${LT_DISABLE_WEB_UI}
      LT_DISABLE_FILES_TRANSLATION: ${LT_DISABLE_FILES_TRANSLATION}

volumes:
  postgres_data:
